# Site settings
title: Service as a Service
email: Vertrieb@ServiceAsAService.de
description: >
  Werden Sie Microsoft Partner mit uns als erfahrenem Guide. Nutzen Sie Azure Gutschriften, Produktlizenzen, Co-Selling und mehr.
logo: /assets/images/logo.jpg # Open Graph/Twitter default site image Path
baseurl: # the subpath of your site, e.g. /blog
url: www.serviceasaservice.de # the base hostname & protocol for your site
author: ServiceAsAService GmbH # default Author
bio:
author_image: "/assets/images/author.jpg"
github_username:  Gott50

#Mailchimp Form URL
fsrc:

# Google Analytics
analytics_id:

# Plugin: Paginate
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: /blog/page:num/ # Path to index.html of your Blog
permalink: /blog/:categories/:title/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugin: SEO-Tags
lang: "de_DE"
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
## Social Sharing
twitter:
  username:
facebook:
  app_id: # a Facebook app ID for Facebook insights
  publisher: # a Facebook page URL or ID of the publishing entity
  admins: # a Facebook user ID for domain insights linked to a personal account

# For specifying social profiles / SEO-Tags
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Collections
collections:
  testimonials:
    output: true
    permalink: /:collection/:title/
  courses:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  # default
  - scope:
      path: ""
    values:
      image: /assets/images/author.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
      navigation: true
  # _courses
  - scope:
      path: ""
      type: courses
    values:
      layout: page
      meta: Course


# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

# Reading Files
include:
  - .htaccess
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - .idea
